name: 'Auto Update PRs'
description: 'A GitHub Action that auto-updates PRs with changes from their base branch'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-pull-request'
  color: 'blue'
